services:
  - type: web
    name: meteord-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: WEATHERAPI_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ONAMET_SIMULATE_EMERGENCY
        value: false
      - key: ONAMET_SIMULATE_WATCH
        value: false
